### ISSUE TITLE
show AQI if CDSC Station is offline

### ISSUE THREAD

**Issue by zefanja** [cdscacth/AQI#1]
Hi @aPinat,

it would be nice if there is still an AQI displayed, even when our station or GIS's one is offline. Just show "Offline" if we can't get any value from the stations.

Thanks for all your effort! I really appreciate that!

**Comment by aPinat** [comment]
Well... I did talk to Pos about that... Issue is, that it's not the actual "purpose" of the site, because the resulting AQI displayed at the top is composed mainly of the CDSC's value...

But, I'll check, how I could still change it, when some values are available...

**Comment by zefanja** [comment]
yes, that's true, but IMHO it does not help to decide what to do, if there is just a white screen if we could use the measurements of the other stations.

Anyway...have a nice weekend!
