### ISSUE TITLE
use some kind of storage backend

### ISSUE THREAD

**Issue by zefanja** [cdscacth/AQI#2]
One suggestion: you could use [localForage](https://localforage.github.io/localForage/) to save the values instead of putting them in hidden html tags. Or use plain localStorage API, but it just can store strings (and you have to use JSON.parse, parseFloat, ... by your self again). LocalForage takes care of that by itself.

**Comment by aPinat** [comment]
Took me quite some time to realize, that localForage works async... But seems to work now.

**Comment by zefanja** [comment]
> Took me quite some time to realize, that localForage works async...

This also happens to me when I've started to work with Javascript :smile:
